---
name: C/C++ CI

on:
  schedule:
    - cron: "0 13 4 * 5"  # run test once a month
  push:
    branches:
      - master
      - develop

    paths:
      - configure.ac
      - 'src/**'
      - 'include/**'
      - .github/workflows/*.yml

  pull_request:
    branches: [master]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notify start to gitlama
    steps:
      - name: IRC notification
        uses: LanguageMachines/ticcactions/irc-init@v1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  build:
    needs: notification
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++-12, clang++]

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: LanguageMachines/ticcactions/cpp-build-env@v1
      - uses: LanguageMachines/ticcactions/cpp-dependencies@v1
      - uses: LanguageMachines/ticcactions/add-textcat@v1
      - uses: LanguageMachines/ticcactions/setup-cppcheck@v1
      - uses: LanguageMachines/ticcactions/irc-nick@v1

      - uses: LanguageMachines/ticcactions/cpp-submodule-build@v1
        with:
          module: ticcutils

      - uses: LanguageMachines/ticcactions/cpp-submodule-build@v1
        with:
          branch: ${{ github.ref_name }}
          module: libfolia

      - uses: LanguageMachines/ticcactions/cpp-submodule-build@v1
        with:
          module: uctodata

      - uses: LanguageMachines/ticcactions/cpp-submodule-build@v1
        with:
          module: ucto

      - name: Static Code-check
        if: ${{ env.action_status == '' }}
        run: cppcheck ${{ env.cpc_opts }} .

      - uses: LanguageMachines/ticcactions/cpp-safe-build@v1

      - name: Notify IRC of end result
        uses: LanguageMachines/ticcactions/irc-status@v1
        with:
          branch: ${{ github.ref_name }}
          nickname: ${{ env.nick }}
          step: build
          status: ${{ env.action_status }}
          details: ${{ env.action_details }}
        continue-on-error: true
